modLoader="javafml"
loaderVersion="[31,)"

issueTrackerURL="https://github.com/Yunus1903/Exorcery/issues"

[[mods]]
    modId="exorcery"
    version="${file.jarVersion}"
    displayName="Exorcery"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/exorcery"
    logoFile="exorcery.png"

    authors="Yunus1903"
    credits=""
    description='''
    '''

[[dependencies.exorcery]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
[[dependencies.exorcery]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
