modLoader="javafml"
loaderVersion="[${loader_version},)"
issueTrackerURL="https://github.com/Yunus1903/Exorcery/issues"

[[mods]]
    modId="exorcery"
    version="${version}"
    displayName="Exorcery"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/exorcery"
    logoFile="exorcery.png"

    authors="Yunus1903"
    credits=""
    description="Exorcery will give you the ability to cast spells and feel the sense of magic and sorcery flow trough you."

[[dependencies.exorcery]]
    modId="minecraft"
    mandatory=true
    versionRange="[${minecraft_version}]"
    ordering="NONE"
    side="BOTH"
[[dependencies.exorcery]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version},)"
    ordering="NONE"
    side="BOTH"
